version: "3"
services:
  reverse-proxy:
    platform: linux/amd64
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - my-service
    links:
      - my-service
  my-service:
    platform: linux/amd64
    build: .
    ports:
      - 8080:8080