version: "3"
services:
  web:
    platform: linux/amd64
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
  spring:
    platform: linux/amd64
    build: .
    ports:
      - 8080:8080